package main

import (
	"encoding/json"
	"encoding/xml"
	"flag"
	"fmt"
	"os"
	"strings"
)

// XML structure to parse <inputData> tags
type InputData struct {
	XMLName xml.Name `xml:"inputData"`
	Name    string   `xml:"name,attr"`
}

// parseType determines the Go type for a given JSON value.
func parseType(value interface{}) string {
	switch v := value.(type) {
	case string:
		return "string"
	case bool:
		return "bool"
	case float64: // JSON numbers are decoded into float64 by default
		return "float64"
	case []interface{}:
		if len(v) == 0 {
			return "[]string"
		}
		if _, ok := v[0].(string); ok {
			return "[]string"
		}
		return "[]interface{}"
	default:
		return "interface{}"
	}
}

// deriveStruct generates a Go struct definition from a JSON object in order.
func deriveStruct(structName string, jsonObj map[string]interface{}) (string, map[string]string) {
	var sb strings.Builder
	fieldMap := make(map[string]string)

	sb.WriteString(fmt.Sprintf("type %s struct {\n", structName))

	// Preserve order by iterating over the JSON object keys
	for key, value := range jsonObj {
		fieldName := strings.Title(key)
		fieldType := parseType(value)
		fieldMap[fieldName] = fieldType // Store for matching later
		jsonTag := fmt.Sprintf("`json:\"%s\"`", key)
		sb.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldName, fieldType, jsonTag))
	}

	sb.WriteString("}\n")
	return sb.String(), fieldMap
}

// deriveStructLight generates a smaller struct based on selected fields from XML.
func deriveStructLight(structName string, fieldMap map[string]string, xmlFields []string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("type %sLight struct {\n", structName))

	for _, xmlField := range xmlFields {
		field := strings.Title(xmlField) // Ensure XML fields are properly title-cased
		if fieldType, exists := fieldMap[field]; exists {
			jsonTag := fmt.Sprintf("`json:\"%s\"`", xmlField)
			sb.WriteString(fmt.Sprintf("\t%s %s %s\n", field, fieldType, jsonTag))
		}
	}

	sb.WriteString("}\n")
	return sb.String()
}

// parseXML extracts input labels from the DMN XML file.
func parseXML(filePath string) ([]string, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, err
	}

	type Input struct {
		Label string `xml:"label,attr"`
	}

	decoder := xml.NewDecoder(strings.NewReader(string(data)))
	var names []string
	for {
		token, err := decoder.Token()
		if err != nil {
			break
		}
		switch se := token.(type) {
		case xml.StartElement:
			if se.Name.Local == "input" {
				var input Input
				if err := decoder.DecodeElement(&input, &se); err == nil {
					names = append(names, input.Label)
				}
			}
		}
	}

	return names, nil
}

// generateStructScript generates a complete Go script containing the structs and registry.
func generateStructScript(structName, mainStruct, lightStruct string) {
	var sb strings.Builder

	sb.WriteString("package structs\n\n")
	sb.WriteString("import \"reflect\"\n\n")

	sb.WriteString("var StructRegistry = map[string]reflect.Type{\n")
	sb.WriteString(fmt.Sprintf("\t\"%s\": reflect.TypeOf(%s{}),\n", structName, structName))
	sb.WriteString(fmt.Sprintf("\t\"%sLight\": reflect.TypeOf(%sLight{}),\n", structName, structName))
	sb.WriteString("\t// Add other structs here if needed\n")
	sb.WriteString("}\n\n")

	sb.WriteString(mainStruct + "\n")
	sb.WriteString(lightStruct + "\n")

	// Write the script to a file called "structs.go"
	outputFile := "../utils/structures/structs.go"
	err := os.WriteFile(outputFile, []byte(sb.String()), 0644)
	if err != nil {
		fmt.Println("Error writing to structs.go:", err)
		return
	}

	fmt.Println("Structs generated and saved to structs.go.")
}

func main() {
	// Define command-line flags
	structName := flag.String("struct_name", "AutoGeneratedStruct", "Name of the generated struct")
	inputFile := flag.String("input_file", "input.json", "Path to the JSON input file")
	decisionInputs := flag.String("decision_inputs", "", "Path to the XML decision inputs file")
	flag.Parse()

	// Read and parse JSON file
	data, err := os.ReadFile(*inputFile)
	if err != nil {
		fmt.Println("Error reading JSON file:", err)
		return
	}

	var rawData []map[string]interface{}
	if err := json.Unmarshal(data, &rawData); err != nil {
		fmt.Println("Error parsing JSON:", err)
		return
	}

	if len(rawData) == 0 {
		fmt.Println("JSON array is empty")
		return
	}

	// Check length of JSON and select first entry
	jsonObj := rawData[0]
	if len(rawData) > 1 {
		fmt.Printf("JSON has %d entries, using the first entry for struct generation.\n", len(rawData))
	}

	// Generate main struct (use selected object for field extraction)
	mainStruct, fieldMap := deriveStruct(*structName, jsonObj)

	// Process XML for StructLight
	var lightStruct string
	if *decisionInputs != "" {
		xmlFields, err := parseXML(*decisionInputs)
		if err != nil {
			fmt.Println("Error parsing XML file:", err)
			return
		}
		lightStruct = deriveStructLight(*structName, fieldMap, xmlFields)
	}

	// Generate and save the full Go script into "structs.go"
	generateStructScript(*structName, mainStruct, lightStruct)
}
