package main

import (
	"encoding/json"
	"encoding/xml"
	"flag"
	"fmt"
	"os"
	"strings"
)

// parseType determines the Go type for a given JSON value.
func parseType(value interface{}) string {
	switch v := value.(type) {
	case string:
		return "string"
	case bool:
		return "bool"
	case float64: // JSON numbers are decoded into float64 by default
		return "float64"
	case []interface{}:
		if len(v) == 0 {
			return "[]string"
		}
		if _, ok := v[0].(string); ok {
			return "[]string"
		}
		return "[]interface{}"
	default:
		return "interface{}"
	}
}

// deriveStruct generates a Go struct definition from a JSON object.
func deriveStruct(structName string, jsonObj map[string]interface{}) (string, map[string]string) {
	var sb strings.Builder
	fieldMap := make(map[string]string)

	sb.WriteString(fmt.Sprintf("type %s struct {\n", structName))

	for key, value := range jsonObj {
		fieldName := strings.Title(key)
		fieldType := parseType(value)
		fieldMap[fieldName] = fieldType
		jsonTag := fmt.Sprintf("`json:\"%s\"`", key)
		sb.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldName, fieldType, jsonTag))
	}

	sb.WriteString("}\n")
	return sb.String(), fieldMap
}

// deriveStructLight generates a smaller struct based on selected fields from XML.
func deriveStructLight(structName string, fieldMap map[string]string, xmlFields []string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("type %sLight struct {\n", structName))

	for _, xmlField := range xmlFields {
		field := strings.Title(xmlField)
		if fieldType, exists := fieldMap[field]; exists {
			jsonTag := fmt.Sprintf("`json:\"%s\"`", xmlField)
			sb.WriteString(fmt.Sprintf("\t%s %s %s\n", field, fieldType, jsonTag))
		}
	}

	sb.WriteString("}\n")
	return sb.String()
}

// DMN input info: label + typeRef from inputExpression
type DMNInputInfo struct {
	Label   string
	TypeRef string
}

// parseXML extracts input labels + typeRef from the DMN XML file.
func parseXML(filePath string) ([]DMNInputInfo, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, err
	}

	type InputExpression struct {
		TypeRef string `xml:"typeRef,attr"`
	}
	type Input struct {
		Label           string          `xml:"label,attr"`
		InputExpression InputExpression `xml:"inputExpression"`
	}

	decoder := xml.NewDecoder(strings.NewReader(string(data)))
	var inputs []DMNInputInfo

	for {
		token, err := decoder.Token()
		if err != nil {
			break
		}
		switch se := token.(type) {
		case xml.StartElement:
			if se.Name.Local == "input" {
				var in Input
				if err := decoder.DecodeElement(&in, &se); err == nil {
					inputs = append(inputs, DMNInputInfo{
						Label:   in.Label,
						TypeRef: in.InputExpression.TypeRef,
					})
				}
			}
		}
	}

	return inputs, nil
}

func addExtraFieldsToStruct(structCode string, extras []string) string {
	idx := strings.LastIndex(structCode, "}\n")
	if idx == -1 || len(extras) == 0 {
		return structCode
	}
	var sb strings.Builder
	sb.WriteString(structCode[:idx])
	for _, line := range extras {
		sb.WriteString(line)
	}
	sb.WriteString(structCode[idx:])
	return sb.String()
}

// generateStructScript generates a complete Go script containing the structs and registry.
func generateStructScript(structName, mainStruct, lightStruct string) {
	var sb strings.Builder

	sb.WriteString("package structs\n\n")
	sb.WriteString("import \"reflect\"\n\n")

	sb.WriteString("var StructRegistry = map[string]reflect.Type{\n")
	sb.WriteString(fmt.Sprintf("\t%q: reflect.TypeOf(%s{}),\n", structName, structName))
	sb.WriteString(fmt.Sprintf("\t%q: reflect.TypeOf(%sLight{}),\n", structName+"Light", structName))
	sb.WriteString("\t// Add other structs here if needed\n")
	sb.WriteString("}\n\n")

	sb.WriteString(mainStruct + "\n")
	if lightStruct != "" {
		sb.WriteString(lightStruct + "\n")
	}

	outputFile := "../utils/structures/structs.go"
	if err := os.WriteFile(outputFile, []byte(sb.String()), 0644); err != nil {
		fmt.Println("Error writing to structs.go:", err)
		return
	}

	fmt.Println("Structs generated and saved to structs.go.")
}

func main() {
	structName := flag.String("struct_name", "AutoGeneratedStruct", "Name of the generated struct")
	inputFile := flag.String("input_file", "input.json", "Path to the JSON input file")
	decisionInputs := flag.String("decision_inputs", "", "Path to the XML decision inputs file")
	flag.Parse()

	data, err := os.ReadFile(*inputFile)
	if err != nil {
		fmt.Println("Error reading JSON file:", err)
		return
	}

	var rawData []map[string]interface{}
	if err := json.Unmarshal(data, &rawData); err != nil {
		fmt.Println("Error parsing JSON:", err)
		return
	}

	if len(rawData) == 0 {
		fmt.Println("JSON array is empty")
		return
	}

	jsonObj := rawData[0]
	if len(rawData) > 1 {
		fmt.Printf("JSON has %d entries, using the first entry for struct generation.\n", len(rawData))
	}

	mainStruct, fieldMap := deriveStruct(*structName, jsonObj)

	var lightStruct string
	if *decisionInputs != "" {
		dmnInputs, err := parseXML(*decisionInputs)
		if err != nil {
			fmt.Println("Error parsing XML file:", err)
			return
		}

		// fmt.Println("Detected inputs from XML:")
		// for _, in := range dmnInputs {
		// 	fmt.Printf("  label=%q typeRef=%q\n", in.Label, in.TypeRef)
		// }

		var xmlLabels []string
		var extraContextLines []string

		for _, in := range dmnInputs {
			xmlLabels = append(xmlLabels, in.Label)

			// Include additional fields ONLY if missing in JSON AND typeRef="context"
			field := strings.Title(in.Label)
			if _, exists := fieldMap[field]; !exists && in.TypeRef == "context" {
				// context fields in your generator are used as numeric comparisons -> float64
				fieldMap[field] = "float64"
				extraContextLines = append(extraContextLines,
					fmt.Sprintf("\t%s float64 `json:\"%s\"`\n", field, in.Label))
			}
		}

		// Add extra context fields to the main struct too (so they exist in Patient as well)
		mainStruct = addExtraFieldsToStruct(mainStruct, extraContextLines)

		// Now build Light struct using xmlLabels filtered by fieldMap (JSON types + added context extras)
		lightStruct = deriveStructLight(*structName, fieldMap, xmlLabels)
	}

	generateStructScript(*structName, mainStruct, lightStruct)
}